name: flutter_file_manager
description: A modern, fully-featured file explorer for Android devices.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5 # For state management
  file_picker: ^8.0.0 # For picking files
  path_provider: ^2.1.3 # For getting common file system locations
  external_path: ^2.2.0 # For getting external storage paths
  
  sqflite: ^2.3.3+1 # For SQLite tagging system
  firebase_core: ^3.1.0 # For Firebase integration
  firebase_storage: ^12.1.0 # For Firebase storage backup
  intl: ^0.17.0 # For date formatting etc.
  mime: ^1.0.5 # For determining file types
  open_filex: ^4.3.2 # For opening files
  share_plus: ^9.0.0 # For sharing files
  archive: ^3.5.2 # For Zip/Unzip functionality
  local_auth: ^2.2.0 # For biometric authentication
  flutter_secure_storage: ^9.0.0 # For secure storage of PIN/biometric data
  
  # For Material 3 icons, if needed beyond default Material Icons
  # material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
